version: "3.8"

services:
  service1:
    build:
      context: .
      dockerfile: ./service1/Dockerfile
    ports: 
      - "8000:8000"
    networks:
      - app-network

  service2:
    build:
      context: .
      dockerfile: ./service2/Dockerfile
    ports: 
      - "8001:8001"
    networks:
      - app-network
  
  loki:
    image: grafana/loki:2.9.0
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki/loki-config.yml:/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:2.9.0
    container_name: promtail
    volumes:
      - ./promtail/promtail-config.yml:/etc/promtail/config.yml
      - ./logs:/var/log
    command: -config.file=/etc/promtail/config.yml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  grafana-storage:

networks:
  app-network:
    driver: bridge