version: "3.8"

services:
  service1:
    build:
      context: .
      dockerfile: ./service1/Dockerfile
    ports: 
      - "8000:8000"
    networks:
      - app-network
    volumes:
      - ./service1/logs:/var/log/service1

  service2:
    build:
      context: .
      dockerfile: ./service2/Dockerfile
    ports: 
      - "8001:8001"
    networks:
      - app-network
    volumes:
      - ./service2/logs:/var/log/service2

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    volumes:
      - ./loki/loki-config.yml:/etc/loki/loki-config.yaml
    command: -config.file=/etc/loki/loki-config.yaml
    networks:
      - loki
  promtail:
    image: grafana/promtail:latest
    volumes:
      - ./promtail/promtail-config.yml:/etc/promtail/promtail-config.yaml
      - ./service2/logs:/var/log/service2
      - ./service1/logs:/var/log/service1
    command: -config.file=/etc/promtail/promtail-config.yaml
    depends_on:
      - loki   
    networks:
      - loki
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    networks:
      - loki


networks:
  loki:
    driver: bridge
  app-network:
    driver: bridge
